
---
AWSTemplateFormatVersion: '2010-09-09'
#
# Parameters section contains names that are substituted in the Resources section
# These parameters are the names the resources created in the Data Catalog
#
# To clean up resources, simply delete this CloudFormation stack from your CloudFormation console or CLI
#
Parameters:                                                                                                       
# The name of the crawler to be created
  CFNCrawlerName:  
    Type: String
    Default: cfn-crawler-telco-analytics
  CFNDatabaseName:
    Type: String
    Default: cfn-database-telco-analytics
  CFNTablePrefixName:
    Type: String
    Default: cfn_telco_analytics_	
#
# Resources section defines metadata for the Data Catalog
Resources:
#Create IAM Role assumed by the crawler
  CFNRoleTelcoAnalytics:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "glue.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        -
          PolicyName: "Telco-Glue-Crawler"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'glue:*'
                  - 's3:GetBucketLocation'
                  - 's3:ListBucket'
                  - 's3:ListAllMyBuckets'
                  - 's3:GetBucketAcl'
                  - 'ec2:DescribeVpcEndpoints'
                  - 'ec2:DescribeRouteTables'
                  - 'ec2:CreateNetworkInterface'
                  - 'ec2:DeleteNetworkInterface'
                  - 'ec2:DescribeNetworkInterfaces'
                  - 'ec2:DescribeSecurityGroups'
                  - 'ec2:DescribeSubnets'
                  - 'ec2:DescribeVpcAttribute'
                  - 'iam:ListRolePolicies'
                  - 'iam:GetRole'
                  - 'iam:GetRolePolicy'
                  - 'cloudwatch:PutMetricData'
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - 's3:CreateBucket'
                Resource:
                  - 'arn:aws:s3:::aws-glue-*'
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                  - 's3:DeleteObject'
                Resource:
                  - 'arn:aws:s3:::aws-glue-*/*'
                  - 'arn:aws:s3:::*/*aws-glue-*/*'
              - Effect: Allow
                Action:
                  - 's3:GetObject'
                Resource:
                  - 'arn:aws:s3:::crawler-public*'
                  - 'arn:aws:s3:::aws-glue-*'
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource:
                  - 'arn:aws:logs:*:*:/aws-glue/*'
              - Effect: Allow
                Action:
                  - 'ec2:CreateTags'
                  - 'ec2:DeleteTags'
                Condition:
                  'ForAllValues:StringEquals':
                    'aws:TagKeys':
                      - aws-glue-service-resource
                Resource:
                  - 'arn:aws:ec2:*:*:network-interface/*'
                  - 'arn:aws:ec2:*:*:security-group/*'
                  - 'arn:aws:ec2:*:*:instance/*'
 #
 # Create a database to contain tables created by the crawler
  CFNDatabaseTelcoAnalytics:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Ref CFNDatabaseName
        Description: "AWS Glue container to hold tables for the Telco Analytics crawler"
 #
 # Create a crawler to crawl the rawdata on your S3 bucket
  CFNCrawlerTelcoAnalytics:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Ref CFNCrawlerName
      Role: !GetAtt CFNRoleTelcoAnalytics.Arn
      #Classifiers: none, use the default classifier
      Description: AWS Glue crawler to crawl Telco Analytics data
      #Schedule: none, use default run-on-demand
      DatabaseName: !Ref CFNDatabaseName
      Targets:
        S3Targets:
          - Path: "s3://serverless-analytics/telco-data-analytics-blog/rawdata.csv"
      TablePrefix: !Ref CFNTablePrefixName
      SchemaChangePolicy:
        UpdateBehavior: "UPDATE_IN_DATABASE"
        DeleteBehavior: "LOG"
      Configuration: "{\"Version\":1.0,\"CrawlerOutput\":{\"Partitions\":{\"AddOrUpdateBehavior\":\"InheritFromTable\"},\"Tables\":{\"AddOrUpdateBehavior\":\"MergeNewColumns\"}}}"
